bStats: true
server-name: "Example"
discord-bot:
  enabled: false
  token: ""
  status: "Reports on your server"
  activity: WATCHING
  # there must be channel id (you need developer mode for this)
  log-channel: ""
  log-message:
    title: "New report (%player_name%) (Server-%server_name%)"
    color:
      r: 88
      g: 125
      b: 255
    description: "Player %player_name% was reported by %reporter_name%."
    timestamp: true
    thumbnail:
      enabled: true
      url: "https://crafatar.com/renders/head/%player_uuid%"
    field-reason:
      title: "Reason"
      description: "%reason%"
    field-reported:
      title: "Reported by"
      description: "%reporter_name%"
db:
  SQLite:
    useLocal: true
    database: reports
    # if local, leave this as it is
    host: "0.0.0.0"
    port: 3306
    user: "root"
    password: ""
messages:
  player-only: "&cThis command is only for players!"
  no-permissions: "&cYou are not authorised to use this!"
  invalid-use: "&cUse command: &a/%command% %command_args%"
  command:
    args: "(player) (reason)"
  alert: "&aPlayer &b%reporter_name% &areported &c%player_name% &awith reason &c%reason%"
  reported: "&aYou have reported &c%player_name% &awith reason &c%reason%"
  numberexception: "&cZadaný input není číslo!"
  player-result: "&aID: %report_id%&b: &a%reporter_name% &creported &a%player_name% &cwith reason &a%reason%"
  deleted-record: "&aReport with ID &c%report_id% &awas deleted!"
  no-result: "&cNo results were found to this value!"
  report-yourself: "&cYou can't report yourself!"
  invalid-player: "&cThis player wasn't on this server."
  help:
    - "&aAdvancedReport &b- &6Advanced, modern solution"
    - " "
    - "&a/adminreport help"
    - "&a/adminreport id REPORT-ID"
    - "&a/adminreport clear id REPORT-ID"
    - "&a/adminreport player REPORT-NAME"
    - " "
    - "&6spigotmc.org"
report-menu:
  player-head:
    display_name: "&aYou are reporting this guy"
    lore:
      - "&aName: &c%player_name%"
      - "&aReason: &c%reason%"
  yes-button:
    display_name: "&aYes, I want to report!"
    lore:
      - "&aBy clicking on this,"
      - "&ayou will report this player"
      - "&aand you can't take anything back!"
  no-button:
    display_name: "&aNo, this was mistake!"
    lore:
      - "&aYou can cancel report"
      - "&aand don't send anything,"
      - "&aif this was a mistake."